name: Test Homebrew Formula

on:
  workflow_dispatch:

jobs:
  test-brew:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Homebrew (Linux only)
        if: runner.os == 'Linux'
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Install
        run: |
          brew install octelium/tap/octelium
          brew install octelium/tap/cordium

      - name: Verify Binaries
        run: |
          echo "Checking octelium..."
          octelium version
          
          echo "Checking octeliumctl..."
          octeliumctl version
          
          echo "Checking octops..."
          octops version

          cordium version
      
      - name: Test Uninstallation
        run: |
          brew uninstall octelium/tap/octelium
          brew uninstall octelium/tap/cordium

          
          ! command -v octelium
          ! command -v octeliumctl
          ! command -v octops
          ! command -v cordium
          
      - name: Cleanup Tap
        run: brew untap octelium/tap